# Generated by Django 2.1.4 on 2018-12-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181216_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PizzaSize', to_field='size'),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
