# Generated by Django 2.1.4 on 2018-12-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181216_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
