# Generated by Django 2.1.4 on 2018-12-21 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181221_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=datetime.date(2018, 12, 21), max_length=50),
        ),
    ]
