# Generated by Django 2.1.4 on 2018-12-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181221_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='beverage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza',
        ),
    ]
