# Generated by Django 2.1.4 on 2018-12-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orderitem_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='beverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Beverage'),
        ),
    ]
