# Generated by Django 2.1.4 on 2018-12-23 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orderitem_beverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(default=datetime.time(15, 31, 10, 455473), max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=datetime.date(2018, 12, 23), max_length=50),
        ),
    ]
