# Generated by Django 2.1.4 on 2018-12-24 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181223_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'accepted'), ('D', 'delivered'), ('C', 'canceled')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=datetime.date(2018, 12, 24), max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(default='14:49', max_length=50),
        ),
    ]
