# Generated by Django 2.1.4 on 2018-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181224_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(default='14:52', max_length=50),
        ),
    ]
