# Generated by Django 2.1.4 on 2018-12-28 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20181224_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=datetime.date(2018, 12, 28), max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(default='17:51', max_length=50),
        ),
    ]
