# Generated by Django 2.1.4 on 2018-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181228_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(default='18:13', max_length=50),
        ),
    ]
