# Generated by Django 2.1.4 on 2018-12-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20181228_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(default='19:32', max_length=50),
        ),
    ]
